<?php
header('Content-Type:application/json; charset=UTF-8');

$json = array(
    'name'=>'行业文章对应关系',
    'children'=>array(
        array(
            'name'=>'www.pinyuan.cc',
            'children'=>array(
                array(
                    'name'=>'办公家具（1001）'
                ),
                array(
                    'name'=>'办公设备（1002）'
                ),
                array(
                    'name'=>'儿童家具（1003）'
                ),
                array(
                    'name'=>'学校家具（1004）'
                ),
                array(
                    'name'=>'医院家具（1005）'
                ),
                array(
                    'name'=>'图书馆家具（1006）'
                ),
                array(
                    'name'=>'联合办公家具（1007）'
                ),
                array(
                    'name'=>'公寓家具（1008）'
                ),
                array(
                    'name'=>'餐厅家具（1009）'
                ),
                array(
                    'name'=>'酒店家具（1010）'
                ),
                array(
                    'name'=>'零售家具（1011）'
                )
            )
        ),
        array(
            'name'=>'www.china-pinyuan.com',
            'children'=>array(
                array(
                    'name'=>'办公家具（1001）'
                ),
                array(
                    'name'=>'联合办公家具（1007）'
                )
            )
        ),
        array(
            'name'=>'children.pinyuan.cc',
            'children'=>array(
                array(
                    'name'=>'儿童家具（1003）',
                ),
                array(
                    'name'=>'办公家具（1001）',
                )
            )
        ),
        array(
            'name'=>'school.pinyuan.cc',
            'children'=>array(
                array(
                    'name'=>'学校家具（1004）',
                ),
                array(
                    'name'=>'办公家具（1001）',
                )
            )
        ),
        array(
            'name'=>'hospital.pinyuan.cc',
            'children'=>array(
                array(
                    'name'=>'医院家具（1005）',
                ),
                array(
                    'name'=>'办公家具（1001）',
                )
            )
        ),
        array(
            'name'=>'library.pinyuan.cc',
            'children'=>array(
                array(
                    'name'=>'图书馆家具（1006）',
                ),
                array(
                    'name'=>'办公家具（1001）',
                )
            )
        ),
        array(
            'name'=>'office.pinyuan.cc',
            'children'=>array(
                array(
                    'name'=>'联合办公家具（1007）',
                ),
                array(
                    'name'=>'办公家具（1001）',
                )
            )
        ),
        array(
            'name'=>'apartment.pinyuan.cc',
            'children'=>array(
                array(
                    'name'=>'公寓家具（1008）',
                ),
                array(
                    'name'=>'办公家具（1001）',
                )
            )
        ),
        array(
            'name'=>'restaurant.pinyuan.cc',
            'children'=>array(
                array(
                    'name'=>'餐厅家具（1009）',
                ),
                array(
                    'name'=>'办公家具（1001）',
                )
            )
        ),
        array(
            'name'=>'hotel.pinyuan.cc',
            'children'=>array(
                array(
                    'name'=>'酒店家具（1010）',
                ),
                array(
                    'name'=>'办公家具（1001）',
                )
            )
        ),
        array(
            'name'=>'shelf.pinyuan.cc',
            'children'=>array(
                array(
                    'name'=>'零售家具（1011）',
                ),
                array(
                    'name'=>'办公家具（1001）',
                )
            )
        ),
        array(
            'name'=>'www.zmshoo.com',
            'children'=>array(
                array(
                    'name'=>'智美综合（1012）'
                )
            )
        ),
        array(
            'name'=>'cleaner.zmshoo.com',
            'children'=>array(
                array(
                    'name'=>'新风净化（1013）'
                )
            )
        ),
        array(
            'name'=>'water.zmshoo.com',
            'children'=>array(
                array(
                    'name'=>'净水系统（1014）'
                )
            )
        )
    )
);
echo json_encode($json);